# Generated by Django 6.0.2 on 2026-04-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_internal_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_promotion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='admin_promotion_token',
            field=models.CharField(blank=True, help_text='Unique token for admin promotion confirmation', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_admin_promotion',
            field=models.BooleanField(default=False, help_text='User has pending admin promotion that requires email confirmation'),
        ),
    ]
