# Generated by Django 6.0.2 on 2026-06-18 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_platformsetting_employee_userapikey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwallet',
            name='email_validation_balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
