# Generated by Django 6.0.2 on 2026-06-20 07:48

from django.db import migrations, models


def _normalized_name(user):
    raw_name = (getattr(user, 'first_name', '') or '').strip()
    if not raw_name:
        raw_name = (getattr(user, 'username', '') or '').strip()
    if '@' in raw_name:
        raw_name = raw_name.split('@', 1)[0]

    alnum = ''.join(ch for ch in raw_name if ch.isalnum())
    if not alnum:
        alnum = f'U{getattr(user, "id", 0)}'
    if len(alnum) == 1:
        alnum = f'{alnum}X'
    return alnum


def _styled_pair(value, from_start=True):
    if len(value) < 2:
        value = f'{value}X'
    chunk = value[:2] if from_start else value[-2:]
    return f'{chunk[0].upper()}{chunk[1].lower()}'


def _build_mv_id(user, row_id):
    base = _normalized_name(user)
    return f'{_styled_pair(base, True)}MV{int(row_id):08d}{_styled_pair(base, False)}'


def populate_request_ids(apps, schema_editor):
    EmailValidationHistory = apps.get_model('accounts', 'EmailValidationHistory')

    for item in EmailValidationHistory.objects.select_related('user').all().order_by('id'):
        if item.request_id:
            continue
        item.request_id = _build_mv_id(item.user, item.id)
        item.save(update_fields=['request_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_userwallet_email_validation_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailvalidationhistory',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailvalidationhistory',
            name='request_id',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='emailvalidationhistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='smsmessage',
            name='provider_message_id',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.RunPython(populate_request_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='emailvalidationhistory',
            name='request_id',
            field=models.CharField(blank=True, default='', max_length=80, unique=True),
        ),
    ]
