# Generated by Django 6.0.2 on 2026-08-05

import random
import string
from django.db import migrations, models


def _generate_unique_dlr_id(model_class, field_name, length=8, max_attempts=50):
    alphabet = string.ascii_uppercase + string.digits
    attempts = 0
    generated_id = ''.join(random.choice(alphabet) for _ in range(int(length)))

    while model_class.objects.filter(**{field_name: generated_id}).exists() and attempts < max_attempts:
        attempts += 1
        generated_id = ''.join(random.choice(alphabet) for _ in range(int(length)))

    if model_class.objects.filter(**{field_name: generated_id}).exists():
        raise ValueError(f'Could not generate a unique DLR ID for {field_name}')

    return generated_id


def populate_dlr_unique_ids(apps, schema_editor):
    EmailValidationHistory = apps.get_model('accounts', 'EmailValidationHistory')

    for item in EmailValidationHistory.objects.all().order_by('id'):
        if str(getattr(item, 'dlr_unique_id', '') or '').strip():
            continue
        item.dlr_unique_id = _generate_unique_dlr_id(EmailValidationHistory, 'dlr_unique_id', length=8)
        item.save(update_fields=['dlr_unique_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_emailvalidationipwhitelistrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailvalidationhistory',
            name='dlr_unique_id',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.RunPython(populate_dlr_unique_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='emailvalidationhistory',
            name='dlr_unique_id',
            field=models.CharField(blank=True, default='', max_length=8, unique=True),
        ),
    ]
