# Generated by Django 6.1 on 2026-09-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_alter_emailvalidationhistory_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='internalnotification',
            name='inactivity_days_filter',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
