# Generated by Django 6.1 on 2026-09-29 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_internalnotification_inactivity_days_filter'),
        ('accounts', '0031_whatsappaccount_whatsappnumber_and_more'),
    ]

    operations = [
    ]
