# Generated by Django 6.1 on 2026-09-29 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_merge_20260929_1010'),
        ('accounts', '0038_wallet_recharge_type'),
    ]

    operations = [
    ]
