export const COUNTRY_CODES = [
  { name: 'India', iso2: 'IN', dialCode: '+91' },
  { name: 'United States', iso2: 'US', dialCode: '+1' },
  { name: 'United Kingdom', iso2: 'GB', dialCode: '+44' },
  { name: 'Canada', iso2: 'CA', dialCode: '+1' },
  { name: 'Australia', iso2: 'AU', dialCode: '+61' },
  { name: 'Germany', iso2: 'DE', dialCode: '+49' },
  { name: 'France', iso2: 'FR', dialCode: '+33' },
  { name: 'Italy', iso2: 'IT', dialCode: '+39' },
  { name: 'Spain', iso2: 'ES', dialCode: '+34' },
  { name: 'Netherlands', iso2: 'NL', dialCode: '+31' },
  { name: 'United Arab Emirates', iso2: 'AE', dialCode: '+971' },
  { name: 'Saudi Arabia', iso2: 'SA', dialCode: '+966' },
  { name: 'Singapore', iso2: 'SG', dialCode: '+65' },
  { name: 'Malaysia', iso2: 'MY', dialCode: '+60' },
  { name: 'Indonesia', iso2: 'ID', dialCode: '+62' },
  { name: 'Philippines', iso2: 'PH', dialCode: '+63' },
  { name: 'Thailand', iso2: 'TH', dialCode: '+66' },
  { name: 'Japan', iso2: 'JP', dialCode: '+81' },
  { name: 'South Korea', iso2: 'KR', dialCode: '+82' },
  { name: 'China', iso2: 'CN', dialCode: '+86' },
  { name: 'South Africa', iso2: 'ZA', dialCode: '+27' },
  { name: 'Nigeria', iso2: 'NG', dialCode: '+234' },
  { name: 'Kenya', iso2: 'KE', dialCode: '+254' },
  { name: 'Brazil', iso2: 'BR', dialCode: '+55' },
  { name: 'Mexico', iso2: 'MX', dialCode: '+52' },
  { name: 'Argentina', iso2: 'AR', dialCode: '+54' },
];